name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set Git configuration
        run: |
          git config --global user.name "IrinaZhuravel"
          git config --global user.email "irenasuarchive@gmail.com"

      - name: Set up GitHub token
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/IrinaZhuravel/js-hw8.git

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm run deploy
